### ISSUE TITLE
Panopto URL

### ISSUE THREAD

**Issue by MaxAndolini** [chazzox/faster-panopto#7]
You should add more panopto URL types such as panopto.github.edu.xyz. URL is different in schools. Because of this, there are detection problems of the site.

**Comment by chazzox** [comment]
Hi, yeah sorry mb i'll make a simple fix for this tomorrow, you can either build from source or wait till the new build gets approved on your platforms marketplace. This usually takes a couple days. Sorry for the inconvenience

**Comment by patyiscoding** [comment]
From what I can see, this is still an issue unfortunately!

**Comment by chazzox** [comment]
okay so from what i can see all i need to change is this line https://github.com/chazzox/faster-panopto/blob/main/source/background.js#L25. should i set the regex to be as long as the url includes panopto? hard to know what the strange edge cases are here (obviously the current regex is from my intitutions panopto intance). sorry a fix wasn't out earlier, i probably got sidetracked xd.

ill attempt to get a fix out for this soon, ive got some uni work to do first tho lol

**Comment by patyiscoding** [comment]
Yeah, that should work. My uni's edge case is `https://<institution name>.cloud.panopto.eu/Panopto/Pages/Viewer.aspx` followed by URL parameters, so the current regex is failing to match mainly because of `.com`. So confused on why we're using the `.eu` domain lol

**Comment by chazzox** [comment]
have put out a fix, update should be live on the extentions stores within a few days!
